In [1]:
import sympy
import random
import math
import numpy as np
import sys

sys.path.append("..")
import tree_search

In [2]:
def test_syntax_tree():
    
    for _ in range(10):
        stree = tree_search.SyntaxTree.create_random(1, n_coeffs=5, n_coeffs_inner=2, max_depth=5, optfact=tree_search.SympyOperatorFactory())
        tot_coeffs = stree.get_ncoeffs()

        for _ in range(10):
            c = [random.uniform(-2, 2) for _ in range(tot_coeffs)]
            x = random.uniform(-2, 2)
            stree.set_coeffs(c)

            sympy_x = sympy.Symbol('x')
            
            sympy_expr = stree.evaluate(sympy_x)
            actual = sympy.sympify(stree.evaluate(x)).evalf(3)
            target = sympy_expr.evalf(3, subs={sympy_x: x})
            if actual != target: print(f"{actual} != {target} [image]")

            sympy_expr = sympy.diff(sympy_expr, sympy_x)
            actual = sympy.sympify(stree.evaluate_deriv(x)).evalf(3)
            target = sympy_expr.evalf(3, subs={sympy_x: x})
            if actual != target: print(f"{actual} != {target} [deriv]")

test_syntax_tree()

In [7]:
def test_ineq_activation():
    f = lambda x: math.log(x)
    for x in [1, 1.01, 1.001, 0.99, 0.5, 50]:
        y = f(x)
        act = tree_search.get_ineq_activation(y, 0, sigma=1e3)
        print(f"f({x})={y}, act({y})={act}")

test_ineq_activation()

f(1)=0.0, act(0.0)=0.5
f(1.01)=0.009950330853168092, act(0.009950330853168092)=0.9999522904306017
f(1.001)=0.0009995003330834232, act(0.0009995003330834232)=0.7309603268102028
f(0.99)=-0.01005033585350145, act(-0.01005033585350145)=4.316938373451205e-05
f(0.5)=-0.6931471805599453, act(-0.6931471805599453)=9.33263618503283e-302
f(50)=3.912023005428146, act(3.912023005428146)=1.0


In [10]:
ls = [(1,2), (3,4)]
for (a,b) in ls:
    print(f"{a};{b}")

1;2
3;4


In [2]:
poly = tree_search.PolySyntaxTree(3)
poly.set_coeffs(np.array([3, 2, 1]))

x = np.array([0, 1, -2])
print( poly.evaluate(np.array([x])) )
print( poly.evaluate_deriv(np.array([x])) )
print( poly.coeffs )
print( poly.coeffs_deriv )

[[1 6 9]]
[[  2   8 -10]]
[3 2 1]
[6 2]
